# Introduction to Linear Algebra

In this section we are going to go over some basic Linear Algebra operations in Python. <a target="_blank" href="https://colab.research.google.com/github/ChemAI-Lab/Math4Chem/blob/main/website/Lecture_Notes/Coding/intro_linear_algebra.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

From our previous lecture, we saw that under the structure of **tensors** we can define the following structures,
1. **Scalars** -> zero-order tensors
2. **Vectors** -> fist-order tensors
3. **Matrices** -> second-order tensors

In [2]:
# scalar 
x = np.array(10.)
print('scalar')
print('shape', x.shape)
print('---------------')

# vectors
x = np.array([10.])
print('vector')
print('shape', x.shape)

x = np.array([10,11,12,13,14,15])
print('shape', x.shape)
print('---------------')


# matrices
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('matrix')
print(x)
print('shape', x.shape)
print('---------------')

scalar
shape ()
---------------
vector
shape (1,)
shape (6,)
---------------
matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape (3, 3)
---------------


# Operations on Tensors 
In class we saw that tensors can have two types of operations:
1. Elementwise operations
2. Not-elementwise operations 

## Elementwise operations for vectors
1. Scalar multiplication,   ``c*v``
2. Vector addition,  ``u + v``
3. Elementwise multiplication, ``u*v``

In [3]:
# Defining a vector
v = np.array([1, 2, 3])
u = np.array([4, 5, 6])
print("Vector v:", v)

# Basic operations on vectors
print("Scalar multiplication:", 2 * v)
print("Vector addition:", v + u)
print("Elementwise multiplication:",u*v)

Vector v: [1 2 3]
Scalar multiplication: [2 4 6]
Vector addition: [5 7 9]
Elementwise multiplication: [ 4 10 18]


I am a big fan of Numpy; however given that you are new to python we are going to code these three operations from scratch.

In [18]:
# Scalar multiplication
# write a function that iterates over the vector and multiplies each element with c

def scalar_multiplication(c,x):
    cx = x.copy()
    n = x.shape[0] # number of elements
    for i in range(n):
        cx[i] = c*x[i]
    return cx

In [19]:
# test the scalar_multiplication function
x = np.random.uniform(size=(5,)) # random vector
c = 2. # scalar value 
print('vector', x)
print('ours', scalar_multiplication(c, x))
print('Numpy', c*x)

vector [0.96860437 0.24317104 0.14224979 0.91686355 0.76665946]
ours [1.93720874 0.48634208 0.28449958 1.8337271  1.53331892]
Numpy [1.93720874 0.48634208 0.28449958 1.8337271  1.53331892]


In [27]:
# Vector addition
# write a function that computes the addition of two vectors. 

def vector_addition(u,v):
    nu = u.shape[0]
    nv = v.shape[0]
    
    u_plus_v = np.zeros_like(u)
    for i in range(nu):
        u_plus_v[i] = u[i] + v[i]
    return u_plus_v

In [24]:
# test the vector_addition function
u = np.random.uniform(size=(5,))  # random vector
v = np.random.uniform(size=(5,))  # random vector

print('vector u', u)
print('vector v', v)
print('ours', vector_addition(u, v))
print('Numpy', u+v)

vector u [0.91919339 0.54248777 0.87139839 0.24713116 0.81257307]
vector v [0.27523367 0.9397578  0.88050612 0.53049842 0.42636137]
ours [1.19442706 1.48224557 1.75190451 0.77762958 1.23893444]
Numpy [1.19442706 1.48224557 1.75190451 0.77762958 1.23893444]


In [26]:
# test the vector_addition function for two vectors with different dimensions
u = np.random.uniform(size=(5,))  # random vector
v = np.random.uniform(size=(6,))  # random vector

print('vector u', u)
print('vector v', v)
print('ours', vector_addition(u, v))
print('Numpy', u+v)

vector u [0.23958816 0.19458448 0.35661607 0.7616097  0.73557192]
vector v [0.63002631 0.67544285 0.79867713 0.79017802 0.69620514 0.97445557]
ours [0.86961448 0.87002734 1.15529321 1.55178772 1.43177706]


ValueError: operands could not be broadcast together with shapes (5,) (6,) 

# tes