# Introduction to Linear Algebra

In this section we are going to go over some basic Linear Algebra operations in Python. <br>

This tutorial can be deployed in [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ChemAI-Lab/Math4Chem/blob/main/website/Lecture_Notes/Notes/Coding/intro_linear_algebra.ipynb)

In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

From our previous lecture, we saw that under the structure of **tensors** we can define the following structures,
1. **Scalars** -> zero-order tensors
2. **Vectors** -> fist-order tensors
3. **Matrices** -> second-order tensors

In [2]:
# scalar 
x = np.array(10.)
print('scalar')
print('shape', x.shape)
print('---------------')

# vectors
x = np.array([10.])
print('vector')
print('shape', x.shape, x[0])

x = np.array([10,11,12,13,14,15])
print('shape', x.shape)
print('---------------')

# matrix 
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('matrix')
print(x)
print('shape', x.shape)
print('---------------')

scalar
shape ()
---------------
vector
shape (1,) 10.0
shape (6,)
---------------
matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape (3, 3)
---------------


# Operations on Tensors 
In class we saw that tensors can have two types of operations:
1. Elementwise operations
2. Not-elementwise operations 

## Elementwise operations for vectors
1. Scalar multiplication,   ``c*v``
2. Vector addition,  ``u + v``
3. Elementwise multiplication, ``u*v``

In [3]:
# Defining a vector
v = np.array([1, 2, 3])
u = np.array([4, 5,6])
print("Vector u:", u)
print("Vector v:", v)

# Basic operations on vectors using Numpy
print("Scalar multiplication:", 2 * u)
print("Vector addition:", v + u)
print("Elementwise multiplication:", u * v)

Vector u: [4 5 6]
Vector v: [1 2 3]
Scalar multiplication: [ 8 10 12]
Vector addition: [5 7 9]
Elementwise multiplication: [ 4 10 18]


I am a big fan of Numpy; however given that you are new to python we are going to code these three operations from scratch.

In [4]:
# Scalar multiplication
# write a function that iterates over the vector and multiplies each element with c

def scalar_multiplication(c,x):
    cx = x.copy() # vector cx will be the variable to store c*x
    n = x.shape[0] # number of elements
    for i in range(n):
        cx[i] = c*x[i]
    return cx

In [5]:
# test the scalar_multiplication function

x = np.random.uniform(size=(5,)) # random vector
c = 2. # scalar value 

print('vector', x)
print('ours', scalar_multiplication(c, x))
print('Numpy', c*x) # test your implementation is correct

vector [0.74500909 0.31018572 0.33193346 0.28201042 0.58717913]
ours [1.49001818 0.62037145 0.66386691 0.56402083 1.17435826]
Numpy [1.49001818 0.62037145 0.66386691 0.56402083 1.17435826]


In [ ]:
# Vector addition
# write a function that computes the addition of two vectors. 

def vector_addition(u,v):
    nu = u.shape[0]
    nv = v.shape[0]
    
    # vector u_plus_v will be the variable to store u + v
    u_plus_v = np.zeros_like(u) # check what this command does
    
    # code here
    if nu != nv:
        raise ValueError("Vectors must be the same length!")
    
    for i in range(nu):
        u_plus_v[i] = u[i] + v[i]
    
    return u_plus_v

In [9]:
# test the vector_addition function
u = np.random.uniform(size=(4,))  # random vector
v = np.random.uniform(size=(4,))  # random vector

print('vector u', u)
print('vector v', v)
print('ours', vector_addition(u, v))
print('Numpy', u+v)  # test your implementation is correct

vector u [0.48356335 0.7889297  0.54426769 0.12125586]
vector v [0.04011335 0.98923097 0.92717393 0.21319354]
ours [0.5236767  1.77816067 1.47144162 0.3344494 ]
Numpy [0.5236767  1.77816067 1.47144162 0.3344494 ]


In [ ]:
# test the vector_addition function for two vectors with different dimensions
u = np.random.uniform(size=(5,))  # random vector
v = np.random.uniform(size=(6,))  # random vector

print('vector u', u)
print('vector v', v)
print('ours', vector_addition(u, v))
print('Numpy', u+v)  # test your implementation is correct

In [ ]:
# Vector multiplication
# write a function that multiplies two vectors

def vector_multiplication(u, v):
    # code here
    # use the variable named u_times_v to store the multiplication of the two vectors
    
    return u_times_v

In [ ]:
# test the vector_multiplication function for two vectors with different dimensions
u = np.random.uniform(size=(5,))  # random vector
v = np.random.uniform(size=(5,))  # random vector

print('vector u', u)
print('vector v', v)
print('ours', vector_multiplication(u, v))
print('Numpy', u*v)  # test your implementation is correct

There are many other element-wise operations for vectors. <br>
For example, in previous classes we use a function to compute the pressure given a volume. 

Let's use the idea gas law to compute the pressure given a volume at a constant temperature. 
From the well known equation, $PV= nRT$, we get,
$$ 
P = \frac{nRT}{V}
$$

Plot Isotherms of an ideal gas for different temperatures, for simplicity, assume $nR = 1$.


In [ ]:
def pressure_function(V,Ti):
    # Ti is a single temperature value NOT an array.
    # V is an array of volume values
    
    # code here
    # use the variable named P to store the value of pressure at different volumes
    
    return P

In [ ]:
# test your function, plot some isotherms curves
v_min = 10
v_max = 100
n_v_grid = 100
v = np.linspace(v_min, v_max,n_v_grid)
T = 1.

for ti in [100,150,200,250]: # loop over different temperatures
    p = pressure_function(v,ti)

    plt.plot(v, p, label=ti)

plt.legend()
plt.xlabel('Volume',fontsize=18)
plt.ylabel('Pressure',fontsize=18)

## Dot product
As we will see in the course. The **dot product** is one of the most used functions in linear algebra.
$$
\mathbf{u} \cdot \mathbf{v} = \mathbf{u}\top \mathbf{v} = \|\mathbf{u} \| \|\mathbf{v} \| \cos(\theta)
$$

We can also compute the dot product using the following equation,
$$
\mathbf{u} \cdot \mathbf{v} = \sum_{i=0}^{n} u_i v_i
$$

Let's compute the angle $\theta$ using both equations. 
$$
\theta = \cos^{-1} \left (\frac{\sum_{i=0}^{n} u_i v_i}{\|\mathbf{u} \| \|\mathbf{v} \|}\right ),
$$
where, $\cos^{-1}(x)$ is the [arc cosine](https://en.wikipedia.org/wiki/Inverse_trigonometric_functions). <br>

For this task, we are required the following building blocks,
1. The dot product given the sum of the multiplication between the elements of the vectors.
2. The norm of a vector, $\|\mathbf{u} \| = \sqrt{\mathbf{u}\cdot \mathbf{u}}$
3. Arc cosine, which in Numpy is ``np.arccos()``.



# Distance between vectors
We can also quantify the Euclidean distance between vectors. 
$$
d(\mathbf{u},\mathbf{v}) = \sqrt{\sum_{i=1}^n (u_i - v_i)^2 }.
$$

We can also write the Euclidean distance as,
$$
d(\mathbf{u},\mathbf{v}) = \| \mathbf{u} - \mathbf{v} \|_2.
$$

In [ ]:
# at home create a function for the Euclidean distance using all the resources from this tutorial.
def EuclideanDistance_full(u,v):
    # code here
    # use the variable named d to store the value of the Euclidean distance
    
    return d

In [ ]:
# Euclidean distance using Numpy
def EuclideanDistance(u,v):
    uv = u - v
    uv = np.power(uv,2)
    uv_sum = np.sum(uv)
    d = np.sqrt(uv_sum)
    return d

In [ ]:
u = np.random.uniform(size=(5,))  # random vector
v = np.random.uniform(size=(5,))  # random vector

print('vector u', u)
print('vector v', v)

print('ED: ', EuclideanDistance(u,v))

# prove (numerically) that d(u,v) = d(v,u)
# code here


We can use the following function in Numpy to verify our code.<br>
[``np.linalg.norm(x)``](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)

In [ ]:
print('ED(numpy): ', np.linalg.norm(u-v))

# Cross product

Next class, I will introduce to you guys an additional vector operation named **cross product**.<br>
For three dimensional vectors, using the physics notation, $\mathbf{u} = u_x\mathbf{i} + u_y\mathbf{j} + u_z\mathbf{k}$, where $\mathbf{i},\mathbf{j}$ and $\mathbf{k}$ are unitary vectors, the cross product is defined as,
$$
\mathbf{u} \times \mathbf{v} = (u_y v_z - u_z v_y)\mathbf{i} +(u_z v_x - u_x v_z)\mathbf{j} + (u_x v_y - u_y v_x)\mathbf{k}\\
\mathbf{u} \times \mathbf{v} = [u_y v_z - u_z v_y, u_z v_x - u_x v_z,u_x v_y - u_y v_x]
$$

Compute the cross product of two vectors in three dimensions.

You can verify that the cross product using Numpy's cross product function,
[``np.cross()``](https://numpy.org/doc/stable/reference/generated/numpy.cross.html)

In [ ]:
def cross_product(u,v):
    #code here
    zx =        # u_y v_z - u_z v_y
    zy =        # u_z v_x - u_x v_z
    zz =        # u_x v_y - u_y v_x
    
    z = np.array([zx,zy,zz])
    return z
    

In [ ]:
u = np.random.uniform(size=(3,))  # random vector
v = np.random.uniform(size=(3,))  # random vector

print('vector u', u)
print('vector v', v)
print('cross product ', cross_product(u, v))

print('cross product (Numpy) ', np.cross(u,v))